apiVersion: v1
kind: Service
metadata:
  name: game-svc
  labels:
    app: game-svc
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: game-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-svc
  labels:
    app: game-svc
spec:
  replicas: 1 # at the moment use one, need to solve issues for SignalR/WS, see: https://pumpingco.de/blog/using-signalr-in-kubernetes-behind-nginx-ingress
  selector:
    matchLabels:
      app: game-svc
  template:
    metadata:
      labels:
        app: game-svc
    spec:
      containers:
        - name: game-svc
          image: "{{ $.Values.registryUri }}/game-svc:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000