apiVersion: v1
kind: Service
metadata:
  name: game-svc
  labels:
    app: game-svc
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: game-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-svc
  labels:
    app: game-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-svc
  template:
    metadata:
      labels:
        app: game-svc
    spec:
      containers:
        - name: game-svc
          image: "{{ $.Values.registryUri }}/game-svc:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000