apiVersion: v1
kind: Service
metadata:
  name: identity-server
  labels:
    app: identity-server
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: identity-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-server
  labels:
    app: identity-server
spec:
  replicas: 1 # keep it to one, there's an issue with IdentityServer4, it must keep some stuff in memory during signin
  selector:
    matchLabels:
      app: identity-server
  template:
    metadata:
      labels:
        app: identity-server
    spec:
      containers:
        - name: identity-server
          image: "{{ $.Values.registryUri }}/identity-server:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000