apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false" # see https://github.com/kubernetes/ingress-nginx/issues/3511
    #nginx.ingress.kubernetes.io/auth-tls-secret: boardz-tls
    #nginx.ingress.kubernetes.io/auth-tls-verify-client: "true"
    #nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  name: boardz-ingress
spec:
  tls:
    - hosts:
      - boardz.fabien-molinet.fr
      secretName: boardz-tls
  rules:
    - host: boardz.fabien-molinet.fr
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 3000
            path: /(.*)
          - backend:
              serviceName: identity-server
              servicePort: 5000
            path: /api/identity-server/(.*)
          - backend:
              serviceName: game-svc
              servicePort: 5001
            path: /api/game-svc/(.*)
