apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  name: boardz-frontend-ingress
spec:
  tls:
    - hosts:
      - boardz.fabien-molinet.fr
      secretName: boardz-tls
  rules:
    - host: boardz.fabien-molinet.fr
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 3000
            path: /(.*)
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/affinity: cookie # so an app holds connection to the same instance for WebSockets
    nginx.ingress.kubernetes.io/proxy-read-timeout: 3600 # default is 60s which is too little for WebSockets
    nginx.ingress.kubernetes.io/proxy-send-timeout: 3600 # default is 60s which is too little for WebSockets
  name: boardz-game-svc-ingress
spec:
  tls:
    - hosts:
      - boardz.fabien-molinet.fr
      secretName: boardz-tls
  rules:
    - host: boardz.fabien-molinet.fr
      http:
        paths:
          - backend:
              serviceName: game-svc
              servicePort: 5001
            path: /api/game-svc/(.*)
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers: "4 256k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "64k"
    nginx.ingress.kubernetes.io/http2-max-field-size: "16k"
    nginx.ingress.kubernetes.io/http2-max-header-size: "128k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "8 64k"
  name: boardz-identity-ingress
spec:
  tls:
    - hosts:
      - boardz-identity.fabien-molinet.fr
      secretName: boardz-tls
  rules:
    - host: boardz-identity.fabien-molinet.fr
      http:
        paths:
          - backend:
              serviceName: identity-server
              servicePort: 5000