trigger:
  branches:
    include:
    - master
    - develop

variables:
  - group: Azure
  - group: Boardz-KeyVault
  - name: vmImageName
    value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      displayName: Write tls-cert keyvault certificate
      inputs:
        targetType: 'inline'
        script: echo $TLS_CERT | base64 -d > $BUILD/s/src/frontend/tls-cert
      env:
        TLS_CERT: $(tls-cert)
        BUILD: $(Agent.BuildDirectory)

    - task: Docker@2
      displayName: Build and Push
      inputs:
        dockerfile: ./src/frontend/Dockerfile
        buildContext: ./src/frontend
        command: buildAndPush
        repository: frontend
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildNumber)
          latest

    - task: Docker@2
      displayName: Build and Push
      inputs:
        dockerfile: ./src/game-svc/Api/Dockerfile
        buildContext: ./src/game-svc
        command: buildAndPush
        repository: game-svc
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildNumber)
          latest

    - task: Docker@2
      displayName: Build and Push
      inputs:
        dockerfile: ./src/identity-server/BoardIdentityServer/Dockerfile
        buildContext: ./src/identity-server
        command: buildAndPush
        repository: identity-server
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildNumber)
          latest