trigger:
  branches:
    include:
    - master
    - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: ContainerRegistry
  value: boardz

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: '$(ContainerRegistry)'

- task: Docker@2
  displayName: Build and Push
  inputs:
    dockerfile: ./src/game-svc/Api/Dockerfile
    command: buildAndPush
    repository: $(ContainerRegistry)/game-svc
    tags: |
      $(Build.BuildNumber)
      latest

- task: Docker@2
  displayName: Build and Push
  inputs:
    dockerfile: ./src/identity-server/BoardIdentityServer/Dockerfile
    command: buildAndPush
    repository: $(ContainerRegistry)/identity-server
    tags: |
      $(Build.BuildNumber)
      latest

- task: Docker@2
  displayName: Build and Push
  inputs:
    dockerfile: ./src/frontend/Dockerfile
    command: buildAndPush
    repository: $(ContainerRegistry)/frontend
    tags: |
      $(Build.BuildNumber)
      latest