trigger:
  branches:
    include:
    - master
    - develop

variables:
  - group: Azure
  - name: vmImageName
    value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureKeyVault@1
    inputs:
      azureSubscription: $(azureSubscriptionId)
      keyVaultName: $(boardz-kv2)
      secretsFilter: 'tls-cert'
      runAsPreJob: false

    - task: Docker@2
      displayName: Build and Push
      inputs:
        dockerfile: ./src/game-svc/Api/Dockerfile
        buildContext: ./src/game-svc
        command: buildAndPush
        repository: $(containerRegistry)/game-svc
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildNumber)
          latest

    - task: Docker@2
      displayName: Build and Push
      inputs:
        dockerfile: ./src/identity-server/BoardIdentityServer/Dockerfile
        buildContext: ./src/identity-server
        command: buildAndPush
        repository: $(ContainerRegistry)/identity-server
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildNumber)
          latest

    - task: Docker@2
      displayName: Build and Push
      inputs:
        dockerfile: ./src/frontend/Dockerfile
        buildContext: ./src/frontend
        command: buildAndPush
        repository: $(ContainerRegistry)/frontend
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildNumber)
          latest